# Generated by Django 2.2 on 2021-08-30 12:20

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0002_auto_20210830_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetitlemodel',
            name='page_promo',
            field=models.FileField(blank=True, null=True, upload_to=abcompany.models.upload_location),
        ),
    ]
