# Generated by Django 2.2 on 2021-08-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0003_auto_20210830_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('numbers', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
