# Generated by Django 2.2 on 2021-08-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0004_statisticsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsmodel',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
