# Generated by Django 2.2 on 2021-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0006_missionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionmodel',
            name='header_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='header_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='header_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='text_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='missionmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
