# Generated by Django 2.2 on 2021-09-03 05:17

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0008_auto_20210831_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('page_promo', models.FileField(blank=True, null=True, upload_to=abcompany.models.upload_location)),
            ],
            options={
                'verbose_name': 'Missions of the company',
                'verbose_name_plural': 'Missions of the company',
            },
        ),
        migrations.AlterModelOptions(
            name='missionmodel',
            options={'verbose_name': 'Missions and plans', 'verbose_name_plural': 'Missions and plans'},
        ),
    ]
