# Generated by Django 2.2 on 2021-09-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0009_auto_20210903_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymissionmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companymissionmodel',
            name='title_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companymissionmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
