# Generated by Django 2.2 on 2021-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0012_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='position_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
