# Generated by Django 2.2 on 2021-09-03 18:35

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0013_auto_20210903_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=abcompany.models.team_upload_location),
        ),
    ]
