# Generated by Django 2.2 on 2021-09-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0015_vacancymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vacancymodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='vacancymodel',
            name='name_he',
        ),
        migrations.RemoveField(
            model_name='vacancymodel',
            name='name_ru',
        ),
    ]
