# Generated by Django 2.2 on 2021-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0019_remove_vacancymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
