# Generated by Django 2.2 on 2021-09-15 07:12

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0021_auto_20210915_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendResumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=abcompany.models.file_upload_location)),
            ],
        ),
    ]
