# Generated by Django 2.2 on 2021-09-15 12:24

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0023_auto_20210915_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_title', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=abcompany.models.file_upload_location)),
            ],
            options={
                'verbose_name': 'Download files',
                'verbose_name_plural': 'Download files',
            },
        ),
    ]
