# Generated by Django 2.2 on 2021-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0024_downloadsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='description_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='description_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='full_name_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='pre_title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='pre_title_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='downloadsmodel',
            name='pre_title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
