# Generated by Django 2.2 on 2021-09-15 12:54

import abcompany.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0025_auto_20210915_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=abcompany.models.file_upload_location),
        ),
    ]
