# Generated by Django 2.2 on 2021-10-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0027_aboutusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='title_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
