# Generated by Django 2.2 on 2021-10-30 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcompany', '0028_auto_20211030_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusmodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='description_he',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
