# Generated by Django 2.2 on 2021-09-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210903_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetitlemodel',
            options={'verbose_name': 'Page Title', 'verbose_name_plural': 'Page Title'},
        ),
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.CreateModel(
            name='MiniBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.upload_location)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('root_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectModel')),
            ],
            options={
                'verbose_name': 'Project blocks',
                'verbose_name_plural': 'Project blocks',
            },
        ),
    ]
