# Generated by Django 2.2 on 2021-09-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210903_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniblockmodel',
            name='root_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.ProjectModel'),
        ),
    ]
