# Generated by Django 2.2 on 2021-09-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210906_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetitlemodel',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pagetitlemodel',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='pagetitlemodel',
            old_name='title_he',
            new_name='name_he',
        ),
        migrations.RenameField(
            model_name='pagetitlemodel',
            old_name='title_ru',
            new_name='name_ru',
        ),
    ]
