# Generated by Django 2.2 on 2021-09-07 08:38

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210906_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetitlemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_location),
        ),
    ]
