# Generated by Django 2.2 on 2021-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210907_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_published'),
        ),
    ]
