# Generated by Django 2.2 on 2021-09-06 17:17

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210906_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('page_promo', models.FileField(blank=True, null=True, upload_to=portfolio.models.upload_location)),
            ],
            options={
                'verbose_name': 'Page Title',
                'verbose_name_plural': 'Page Title',
            },
        ),
    ]
