# Generated by Django 2.2 on 2021-08-22 00:34

from django.db import migrations, models
import pagesstatic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('position_en', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pagesstatic.models.upload_location)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
