# Generated by Django 2.2 on 2021-08-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesstatic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadersmodel',
            old_name='name_uz',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='leadersmodel',
            old_name='position_uz',
            new_name='position_de',
        ),
    ]
