# Generated by Django 2.2 on 2021-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesstatic', '0002_auto_20210822_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadersmodel',
            old_name='name_de',
            new_name='name_he',
        ),
        migrations.RenameField(
            model_name='leadersmodel',
            old_name='position_de',
            new_name='position_he',
        ),
    ]
