# Generated by Django 2.2 on 2021-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesstatic', '0005_auto_20211019_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='name_he',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
